version: '3.9'

services:
  app:
    container_name: django-app
    build:
      context: .
      dockerfile: Dockerfile.deploy
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: always
    environment:
      # PYTHON_ENV: dev
      PORT: 8000
